[package]
name = "eventedco"
version = "0.1.0"
authors = ["Y. T. Chung <zonyitoo@gmail.com>"]

[lib]
name = "eventedco"

[[bin]]
name = "tcp-echo"
path = "src/main.rs"

[dependencies]
#mio = "*"
coroutine = "*"
log = "*"
env_logger = "*"
clap = "*"

[dependencies.mio]
git = "https://github.com/carllerche/mio.git"
